# Python Review

Goals: 
- recall basic Python vocabulary
- practice markdown

## Libraries and pakcages

**library**: a collection of code that we can use to perform specific tasks in our programs.

**NumPy**:
- core library for numerical computing in Python
- Many other libraries use NumPy arrays as building blocks
- computations on NumPy are optimized for speed and memory usage

Let's import NumPy with **standard abbreviations**

In [1]:
import numpy as np

## Variables

**variable**: a name we assign to a particular object in Python'

Example: 

In [2]:
# Assign a small array to a variable a
a = np.array([[1,1,2], [3,5,8]])

In [3]:
# Run cell with the variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# Use the 'print' function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Objects

**object** (informally speaking) is a bundle of *properties* and *actions* about something specific.

Example:

Object: data frame

Properties: number rows, names of the columns, date created

Actions: selecting a specific row, adding a new column

A variable is the name we give a specific object, and the same object can be referenced by different variables.

In practice, we can often use variable and object interchangeably

## Types

Every object in Python has a **type**. The type tellls us what kind of object it is.

We can also class the type of an object, the **class** of an object an they both mean what kind of object it is.

In [7]:
print(a)

# Check the class/type of a variable/object using the 'type' function

type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

In [17]:
print(a[0,0])

# Check the type of an entry in the array by indexing
type(a[0,0])

3


numpy.int64

Notice that 'type(a[0,0])' is a 'numpy.int64' and not just the standard Python integer type. This is telling us that 1 is an iteger stored as a 64 bit number

In [19]:
a[1,1]

5

## Functions

'print' was out first example of a Python **function**.

Functions take in a set of **arguments**n and those arguments create an **output**.

Argument = Parameter.

We can ask information about a fucntion by executing '?function'



?print

# This information is a **docstring**.

A function has two types of arguments:
    
    - **non-optional argument**: arguments *you* need to specify or the fucntion to do something
    - **optional argument**: arguments that are pre-filled witha default valye by the function. You can override them. 
    Optional arguments appear inside the parenthesis in the form optional_argument=default_value

In [23]:
print('changing the default end argument', end=' :)')

changing the default end argument :)

## Attributes & Methods

An object in Python has attributes and methods. 

Methods are actions that can be applied to an object
Format method(object)

Attributes are properties an object has that can be called
Format: object.attribute

- **attributes**: a property of an object, some piece of information about it 
- **method**: a procedure associated with an object, an action where the main ingredient is the object

**Example**
Attributes for 'numpy.arrays'

We can access a variable's attributes and methods by adding a period '.' at the end of the variable's name.

'variable.method()' or variable.attribute'

In [31]:
a.shape

(2, 3)

In [33]:
type(a.shape)

tuple

In [34]:
# Methods examples
# min() returns the minimum value along a specified axis
a.min(axis=0)

array([1, 1, 2])

## Check-in

We can also call the min method without any parameters

In [35]:
a.min()

1

Remeber: methods are functions associated with an object.

In [37]:
type(a.min)

builtin_function_or_method

## Excercise

1. Read the 'print' function help. What is the type of argument 'sep'?. Is this an optional or non-optional argument? Why?
Optional because there is no default argument

2. Create two new variables, one with the integer value 77 and another with the string 99.


3. Use your variables to print 77%99%77 by changing the value of one of the optional arguments in "print"

In [45]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [61]:
x = 77
y = '99'

In [66]:
print(x, y, x, sep='%')

77%99%77
